spring.application.name=multitenant-electricity-management

spring.datasource.url=jdbc:postgresql://localhost:5432/multitenant_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none

logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.flyway.enabled=false
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

jwt.SECRET="Coditas@12093!18203@91823#09128$30298%30123^76543&12145*12245"
jwt.EXPIRATION=8640000